#Check HQ MALT generated by Sravan
malt_hq <- read.csv(file = "india_malt.csv")
nforms_may <- read.csv(file = "nforms_may.csv")
nforms_may <- nforms_may[nforms_may$Username != "Total",]

malt_hq$unique_int <- 1:nrow(malt_hq)
malt_hq$month <- as.Date(malt_hq$month, "%Y-%m-%d")
malt_hq$user_id <- as.character(malt_hq$user_id)

hq_summary <- malt_hq %>% group_by(domain_name, month) %>% 
  summarise(nuser_app_rows = length(unique(unique_int)), 
            nusers = length(unique(user_id)), 
            nforms = sum(num_of_forms))

nusers_summary <- merge(dp_summary, hq_summary, by.x = "domain", by.y = "domain_name", all = T)
nusers_summary <- arrange(nusers_summary, desc(nusers_may_dp), desc(nusers_june_malt_hq))